# Generated by Django 5.0.3 on 2024-10-01 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('registro', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('modo', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('finalizado', models.BooleanField(blank=True, default=False, null=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=50)),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to=settings.AUTH_USER_MODEL)),
                ('trabajadores', models.ManyToManyField(blank=True, related_name='trabajadores_aviso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aviso',
                'verbose_name_plural': 'avisos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('estado_cambio', 'Cambio de Estado'), ('asignacion_trabajador', 'Asignación de Trabajador')], max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Avisos.aviso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Aviso',
                'verbose_name_plural': 'Historiales de Avisos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='imageComentAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='Avisos/aviso_default.jpg', null=True, upload_to='Avisos')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('aviso', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageComentAvisos', to='Avisos.aviso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageComentAvisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen / comentario',
                'verbose_name_plural': 'Imagenes y comentarios',
                'db_table': 'imagenes_aviso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='trabajadorAsignadoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('aviso', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignamientos', to='Avisos.aviso')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajador asignado',
                'verbose_name_plural': 'Trabajador - asignamiento',
                'db_table': 'trabajador_asignado_aviso',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trabajadorasignadoaviso',
            constraint=models.UniqueConstraint(fields=('aviso', 'trabajador'), name='unico_trabajador_por_aviso'),
        ),
    ]
