# Generated by Django 5.0.3 on 2024-10-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0002_alter_historialaviso_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialaviso',
            name='accion',
            field=models.CharField(choices=[('cambio_de_estado', 'Cambio de Estado'), ('asignacion_de_trabajador', 'Asignación de Trabajador')], max_length=50),
        ),
    ]
