# Generated by Django 5.0.3 on 2024-10-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0004_aviso_latitud_aviso_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadorasignadoaviso',
            name='notificacion_activa',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
