# Generated by Django 5.0.3 on 2024-10-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0005_trabajadorasignadoaviso_notificacion_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('sin_resolver', 'Sin Resolver'), ('cerrado', 'Cerrado')], default='pendiente', max_length=50),
        ),
    ]
