# Generated by Django 5.0.3 on 2024-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaAbonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(blank=True, max_length=5, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('contador', models.CharField(blank=True, max_length=20, null=True)),
                ('lectura', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen_aviso', models.ImageField(blank=True, default='Contadores\\default.jpg', null=True, upload_to='Contadores')),
                ('imagen_contador', models.ImageField(blank=True, default='Contadores\\default.jpg', null=True, upload_to='Contadores')),
                ('fecha_lectura', models.DateField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
                ('grabada', models.BooleanField(default='False', null='False', verbose_name='Grabada')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'Lectura de abonado',
                'verbose_name_plural': 'Lecturas de abonado',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='cambiocontador',
            options={'ordering': ['-created'], 'verbose_name': 'cambio de contador', 'verbose_name_plural': 'cambios de contador'},
        ),
        migrations.AddField(
            model_name='cambiocontador',
            name='actualizado_compass',
            field=models.BooleanField(default='False', null='False', verbose_name='Actualizado en Compass'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='cambiocontador',
            name='fecha_cambio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cambiocontador',
            name='imagen_nuevo',
            field=models.ImageField(blank=True, default='Contadores\\default.jpg', null=True, upload_to='Contadores'),
        ),
        migrations.AlterField(
            model_name='cambiocontador',
            name='imagen_viejo',
            field=models.ImageField(blank=True, default='Contadores\\default.jpg', null=True, upload_to='Contadores'),
        ),
    ]
