# Generated by Django 5.1.2 on 2024-10-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contadores', '0002_lecturaabonado_alter_cambiocontador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiocontador',
            name='actualizado_compass',
            field=models.BooleanField(default=False, verbose_name='Actualizado en Compass'),
        ),
        migrations.AlterField(
            model_name='cambiocontador',
            name='fecha_cambio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cambiocontador',
            name='imagen_nuevo',
            field=models.ImageField(blank=True, default='Contadores/default.jpg', null=True, upload_to='Contadores'),
        ),
        migrations.AlterField(
            model_name='cambiocontador',
            name='imagen_viejo',
            field=models.ImageField(blank=True, default='Contadores/default.jpg', null=True, upload_to='Contadores'),
        ),
    ]
