# Generated by Django 5.0.3 on 2024-10-07 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
            ],
            options={
                'unique_together': {('año', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ControlDiarioLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('punto', models.IntegerField()),
                ('cloro_libre', models.DecimalField(decimal_places=1, help_text='Concentración de Cloro libre en ppm (≤ 1,0 ppm)', max_digits=3)),
                ('cloro_combinado', models.DecimalField(decimal_places=1, help_text='Concentración de Cloro combinado en ppm (≤ 2,0 ppm)', max_digits=3)),
                ('ph', models.DecimalField(decimal_places=1, help_text='Nivel de pH (6,5 – 9,5)', max_digits=3)),
                ('turbidez', models.DecimalField(decimal_places=1, help_text='Nivel de turbidez en UNF (≤ 4 UNF)', max_digits=3)),
                ('control_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='Personal_Red.controldiario')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_mensuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('control_diario', 'dia')},
            },
        ),
    ]
