# Generated by Django 5.0.3 on 2024-10-07 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Red', '0002_controldiario_created_controldiario_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='controldiariolinea',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_mensuales', to=settings.AUTH_USER_MODEL),
        ),
    ]
