# Generated by Django 5.0.3 on 2024-10-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Red', '0003_alter_controldiariolinea_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controldiariolinea',
            name='punto',
            field=models.CharField(max_length=100),
        ),
    ]
