# Generated by Django 5.0.3 on 2024-10-08 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Red', '0004_alter_controldiariolinea_punto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='controldiariolinea',
            name='punto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='controldiariolinea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_mensuales', to=settings.AUTH_USER_MODEL),
        ),
    ]
