# Generated by Django 5.0.3 on 2024-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaHoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.CharField(max_length=100)),
                ('fecha_hoja', models.CharField(max_length=25, verbose_name='Fecha de hoja')),
                ('siete', models.CharField(blank=True, max_length=500, null=True, verbose_name='07:00')),
                ('sieteymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='07:30')),
                ('ocho', models.CharField(blank=True, max_length=500, null=True, verbose_name='08:00')),
                ('ochoymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='08:30')),
                ('nueve', models.CharField(blank=True, max_length=500, null=True, verbose_name='09:00')),
                ('nueveymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='09:30')),
                ('diez', models.CharField(blank=True, max_length=500, null=True, verbose_name='10:00')),
                ('diezymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='10:30')),
                ('once', models.CharField(blank=True, max_length=500, null=True, verbose_name='11:00')),
                ('onceymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='11:30')),
                ('doce', models.CharField(blank=True, max_length=500, null=True, verbose_name='12:00')),
                ('doceymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='12:30')),
                ('trece', models.CharField(blank=True, max_length=500, null=True, verbose_name='13:00')),
                ('treceymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='13:30')),
                ('catorce', models.CharField(blank=True, max_length=500, null=True, verbose_name='14:00')),
                ('catorceymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='14:30')),
                ('quince', models.CharField(blank=True, max_length=500, null=True, verbose_name='15:00')),
                ('quinceymedia', models.CharField(blank=True, max_length=500, null=True, verbose_name='15:30')),
                ('extra_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Extra - 1')),
                ('extra_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Extra - 2')),
                ('extra_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Extra - 3')),
                ('extra_4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Extra - 4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
        ),
    ]
