# Generated by Django 5.1.2 on 2024-10-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSumarteApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaHoja',
        ),
    ]
